cupcakeshop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cupcakeshop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'', include('menu.urls', namespace='menu')),
)

menu/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.getPostList, name="post_list"),
	url(r'^post/(?P<pk>\d+)/$',views.post_detail,name="post_detail")
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Cupcake(models.Model):
	name = models.CharField(max_length=200)
	price = models.CharField(max_length=20)
	rating = models.FloatField()
	image = models.ImageField(upload_to="post_images")
	writer = models.ForeignKey(User)
	createdAt = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
			return self.name
		
class Post(models.Model):
	name = models.CharField(max_length=20)
	content = models.CharField(max_length=200)
	best = models.IntegerField()
	writer = models.ForeignKey(User)
	createdAt = models.DateTimeField(default=timezone.now)
	def __str__(self):
			return self.name
	
	

menu/views.py
from django.shortcuts import render
from . import models
from .models import Cupcake
from .models import Post
from django.shortcuts import render, get_object_or_404


def getPostList(request):
	posts = Post.objects.all().order_by('-createdAt')
	context = {"posts": posts}
	return render(request,"menu/list.html",context)

def	post_detail(request,pk):
	post = get_object_or_404(Post, pk=pk)
	context = {"post": post}
	return render(request, "menu/detail.html", context)

menu/templates/menu/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>오늘의 베스트</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'menu/css/style.css' %}">
</head>
<body>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">오늘의 베스트!</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" role="button" >New <span class="caret"></span></a>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

    {% block content %}
    {% endblock %}

  <footer class="footer">
      <div class="container">
        <p class="text-muted">204 JUNSEOK OH, GIHEON LEE</p>
      </div>
    </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" ></script>
</body>
</html>

menu/templates/menu/detail.html
{% extends 'menu/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="container">
    {% if post %}
    <h2 class="text-center">게시글 보기</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
          <div class="card">
        <ul class="list-group">
          <li class="list-group-item"><span class="glyphicon glyphicon-tag"></span>  <strong>{{ post.name }}</strong></li>
          <li class="list-group-item"><span class="glyphicon glyphicon-usd"></span>{{post.best}}</li>
          <li class="list-group-item"><span class="glyphicon glyphicon-pencil"></span> {{ post.writer }}</li>
          <li class="list-group-item"><span class="glyphicon glyphicon-calendar"></span>{{ post.createdAt }}</li>
          <li class="list-group-item">{{ post.content }}</li>
          <li class="list-group-item">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
              Like!
            </button>
             </li>
        </ul>
      </div>
    </div>
    </div>
    {% else %}
    <h2 class="text-center">게시글이 존재하지 않습니다.(</h2>
    {% endif %}
  </div>
  <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{{ post.name }}</h4>
      </div>
      <div class="modal-body">
        <p>추천하였습니다!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

menu/templates/menu/list.html
{% extends 'menu/base.html' %}
{% load staticfiles %}
{% block content %}

  <div class="container" style="margin-top:20px">
	<!-- Main component for a primary marketing message or call
	to action -->
	<div class="jumbotron title text-center" style="background-size : cover; background-image: url({% static 'menu/images/KakaoTalk_20161120_040836461.png' %});")>
		<h1 style="font-size : 40px; font-weight : bold">오늘의 베스트는 자유로운 자신의 일상 공간입니다</h1>
		<p>자신의 일상을 마음껏 공유해주세요!</p>
	</div>
	</div> <!-- /container -->
	<div class="container">
		{% if posts %}
		<h3 class="text-center">오늘의 베스트를 구경하고 추천해주세요!</h3>
		<div class="row">
		{% for post in posts %}
		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
		<div class="card">
		<div class="card-img-top">
	</div>
	<div class="card-block">
		<h4 class="card-title text-center">{{ post.name }}</h4>
		<h5 class="card-content text-center">{{ post.content }}</h5>

		<p class="card-text text-center">
		<span class="glyphicon glyphicon-star" aria-hidden="
		true"></span>
		</p>
		<a href="{%	url	'menu:post_detail' pk=post.pk %}" class="btn btn-default btn-lg btn-block">Like!</a>
			</div>
		</div>
	</div>
	{% endfor %}
	</div>
	{% else %}
	<h2 class="text-center">아직 작성된 포스트가 없습니다. -:(</h2>
	{% endif %}
</div>
{% endblock %}